version: '3.3'

services:
  web:
    container_name: og_links_container
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    image: og_links_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
      - ./media/images:/media/images
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres:12.13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=${PGDATA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
